### PR TITLE
fix date formats in responses

### LINKED ISSUE #7: Dates serialization
Dates are not serialized in a proper way

### PR DESCRIPTION
**Pull request by VCGDEV**
This MR fixes #7

### CODE REVIEW

File: src/main/java/com/conta/cloud/sat/dto/AduanaDTO.java [hunk 1]
```diff
@@ -14,6 +14,6 @@
 public class AduanaDTO {
 	private String id;
 	private String descripcion;
-	private Date fechaInicio;
```
Comment (VCGDEV) [inline src/main/java/com/conta/cloud/sat/dto/AduanaDTO.java:17]: remove unused import

File: src/main/java/com/conta/cloud/sat/dto/CodigoPostalDTO.java [hunk 2]
```diff
@@ -27,8 +27,8 @@
 	private Boolean estimuloEnFrontera;
 	
 	@ApiModelProperty(name = "fechaInicio", value = "Fecha inicial para utilizar el codigo postal", required = true)
-	private Date fechaInicio;
+	private String fechaInicio;
```
Comment (VCGDEV) [inline src/main/java/com/conta/cloud/sat/dto/CodigoPostalDTO.java:28]: remove unused import

File: src/main/java/com/conta/cloud/sat/mappers/UnidadMapper.java [hunk 3]
```diff
@@ -16,13 +15,9 @@
...
         @Mapping(source = "idUnidad", target = "id"),
-        @Mapping(source = "fechaInicio", target = "fechaInicio", qualifiedByName = "dateToString"), 
-        @Mapping(source = "fechaFin", target = "fechaFin", qualifiedByName = "dateToString"),
+        @Mapping(target= "fechaInicio", expression = "java(com.conta.cloud.sat.util.DateUtils.fromDate(unidad.getFechaInicio()))"),
+		@Mapping(target= "fechaFin", expression = "java(com.conta.cloud.sat.util.DateUtils.fromDate(unidad.getFechaFin()))")
     })
     UnidadDTO fromEntity(Unidad unidad);
 
-    @Named("dateToString")
-    default String dateToString(Date date) {
```
Comment (VCGDEV) [inline src/main/java/com/conta/cloud/sat/mappers/UnidadMapper.java:25]: remove unused import

**Review by VCGDEV — COMMENTED** [review]
approved
